##spring.datasource.url = jdbc:postgresql://localhost:5432/lovelypet
##spring.datasource.driverClassName = org.postgresql.Driver
##spring.datasource.username = postgres
##spring.datasource.password = Tee192414+
##spring.jpa.hibernate.ddl-auto = create
##spring.jpa.show-sql = true

##spring.servlet.multipart.enabled=true
##spring.servlet.multipart.max-file-size=2MB
##spring.servlet.multipart.max-request-size=5MB
server:
  port: 8080
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: testbackendproject1
    password: allqyeggimprlqnq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/lovely_pet
    username: postgres
    password: Tee192414+

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 100MB
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300000

---
app:
  token:
    secret: n#MySecret9863656GGMPf
    issuer: HotelPetService
  email:
    from: testbackendproject1@gmail.com
